projects:
  app:
    schemaPath: "graphql/schema.graphql"
    includes: ["**/*.graphql"]
    extensions:
      endpoints:
        default: "${env:PRISMA_ENDPOINT}"
  prisma:
    schemaPath: "graphql/generated/prisma.graphql"
    includes: ["**/*.graphql"]
    extensions:
      prisma: prisma/prisma.yml
