projects:
  app:
    schemaPath: "src/database/graphql/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4466"
  prisma:
    schemaPath: "src/database/graphql/generated/prisma.graphql"
    extensions:
      prisma: prisma/prisma.yml
