version: '3'
services:

  prisma-dev:
    image: prismagraphql/prisma:1.25
    restart: always
    depends_on:
      - mysql-dev
    ports:
      - "${PRISMA_PORT}:${PRISMA_PORT}"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: "${PRISMA_MANAGEMENT_API_SECRET}"
        port: ${PRISMA_PORT}
        databases:
          default:
            connector: mysql
            migrations: true
            host: mysql-dev
            port: 3306
            user: root
            password: "${SQL_PASSWORD}"

  prisma-test:
    image: prismagraphql/prisma:1.25
    restart: always
    depends_on:
      - mysql-test
    ports:
      - "${TEST_PRISMA_PORT}:${TEST_PRISMA_PORT}"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: ${TEST_PRISMA_PORT}
        databases:
          default:
            connector: mysql
            migrations: true
            host: mysql-test
            port: 3306
            user: root
            password: "${SQL_PASSWORD}"
            
  mysql-dev:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${SQL_PASSWORD}"
    ports:
     - "${SQL_PORT}:3306"
    volumes:
    - mysql:/var/lib/mysql
    # - ./custom/:/etc/mysql/conf.d/my.cnf

  mysql-test:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${SQL_PASSWORD}"
    ports:
     - "${TEST_SQL_PORT}:3306"

volumes:
  mysql: